name: CodeCov Analysis
on: [push, pull_request]
permissions: write-all


jobs:
  run-linters:
    name: Run analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      
    steps:
    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
