name: ESLint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install modules
      run: npm install
      
    - name: Lint Action #wearerequired/lint-action
      uses: wearerequired/lint-action@v1.10.0
      
    - name: Run ESLint with reviewdog #ESLint Review Dog
      uses: reviewdog/action-eslint@v1.14.0
