name: ESLint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install modules
      run: npm install
      
    - name: Install ESLint #ESLint
      run: npm install -g eslint
      
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
      
    - name: Run eslint with reviewdog #ESLint Review Dog
      uses: reviewdog/action-eslint@v1.14.0
